window.BOOTS_DATA = [
  {
    "id": "ballast",
    "name": "Ballast",
    "overtaking": 0,
    "defending": 0,
    "raceStart": 5,
    "tyreMgmt": 0,
    "speed": 0,
    "cornering": 10,
    "powerUnit": 0,
    "pitTime": 5,
    "total": 20,
    "sourceIndex": 1
  },
  {
    "id": "butterfly",
    "name": "Butterfly",
    "overtaking": 0,
    "defending": 0,
    "raceStart": 0,
    "tyreMgmt": 20,
    "speed": 0,
    "cornering": 0,
    "powerUnit": 25,
    "pitTime": 5,
    "total": 50,
    "sourceIndex": 2
  },
  {
    "id": "champion",
    "name": "Champion",
    "overtaking": 0,
    "defending": 0,
    "raceStart": 10,
    "tyreMgmt": 0,
    "speed": 25,
    "cornering": 0,
    "powerUnit": 15,
    "pitTime": 0,
    "total": 50,
    "sourceIndex": 3
  },
  {
    "id": "christmas",
    "name": "Christmas",
    "overtaking": 10,
    "defending": 0,
    "raceStart": 0,
    "tyreMgmt": 0,
    "speed": 20,
    "cornering": 20,
    "powerUnit": 0,
    "pitTime": 0,
    "total": 50,
    "sourceIndex": 4
  },
  {
    "id": "confetti",
    "name": "Confetti",
    "overtaking": 10,
    "defending": 0,
    "raceStart": 25,
    "tyreMgmt": 0,
    "speed": 0,
    "cornering": 0,
    "powerUnit": 0,
    "pitTime": 15,
    "total": 50,
    "sourceIndex": 5
  },
  {
    "id": "cranberry",
    "name": "Cranberry",
    "overtaking": 20,
    "defending": 20,
    "raceStart": 0,
    "tyreMgmt": 0,
    "speed": 0,
    "cornering": 10,
    "powerUnit": 0,
    "pitTime": 0,
    "total": 50,
    "sourceIndex": 6
  },
  {
    "id": "crown",
    "name": "Crown",
    "overtaking": 0,
    "defending": 5,
    "raceStart": 0,
    "tyreMgmt": 20,
    "speed": 0,
    "cornering": 0,
    "powerUnit": 0,
    "pitTime": 25,
    "total": 50,
    "sourceIndex": 7
  },
  {
    "id": "cuppa",
    "name": "Cuppa",
    "overtaking": 10,
    "defending": 0,
    "raceStart": 20,
    "tyreMgmt": 0,
    "speed": 0,
    "cornering": 20,
    "powerUnit": 0,
    "pitTime": 0,
    "total": 50,
    "sourceIndex": 8
  },
  {
    "id": "dead_fast",
    "name": "Dead Fast",
    "overtaking": 0,
    "defending": 0,
    "raceStart": 0,
    "tyreMgmt": 5,
    "speed": 25,
    "cornering": 0,
    "powerUnit": 20,
    "pitTime": 0,
    "total": 50,
    "sourceIndex": 9
  },
  {
    "id": "djinn",
    "name": "Djinn",
    "overtaking": 0,
    "defending": 15,
    "raceStart": 0,
    "tyreMgmt": 0,
    "speed": 0,
    "cornering": 15,
    "powerUnit": 20,
    "pitTime": 0,
    "total": 50,
    "sourceIndex": 10
  },
  {
    "id": "downforce",
    "name": "Downforce",
    "overtaking": 0,
    "defending": 10,
    "raceStart": 0,
    "tyreMgmt": 15,
    "speed": 0,
    "cornering": 5,
    "powerUnit": 0,
    "pitTime": 0,
    "total": 30,
    "sourceIndex": 11
  },
  {
    "id": "dragon",
    "name": "Dragon",
    "overtaking": 20,
    "defending": 0,
    "raceStart": 0,
    "tyreMgmt": 15,
    "speed": 0,
    "cornering": 0,
    "powerUnit": 15,
    "pitTime": 0,
    "total": 50,
    "sourceIndex": 12
  },
  {
    "id": "eagle",
    "name": "Eagle",
    "overtaking": 0,
    "defending": 0,
    "raceStart": 0,
    "tyreMgmt": 20,
    "speed": 15,
    "cornering": 0,
    "powerUnit": 0,
    "pitTime": 15,
    "total": 50,
    "sourceIndex": 13
  },
  {
    "id": "eclipse",
    "name": "Eclipse",
    "overtaking": 15,
    "defending": 0,
    "raceStart": 0,
    "tyreMgmt": 0,
    "speed": 25,
    "cornering": 0,
    "powerUnit": 0,
    "pitTime": 10,
    "total": 50,
    "sourceIndex": 14
  },
  {
    "id": "eggcepton",
    "name": "Eggcepton",
    "overtaking": 0,
    "defending": 15,
    "raceStart": 0,
    "tyreMgmt": 0,
    "speed": 0,
    "cornering": 0,
    "powerUnit": 10,
    "pitTime": 25,
    "total": 50,
    "sourceIndex": 15
  },
  {
    "id": "eternal_flame",
    "name": "Eternal Flame",
    "overtaking": 25,
    "defending": 0,
    "raceStart": 0,
    "tyreMgmt": 10,
    "speed": 15,
    "cornering": 0,
    "powerUnit": 0,
    "pitTime": 0,
    "total": 50,
    "sourceIndex": 16
  },
  {
    "id": "feral",
    "name": "Feral",
    "overtaking": 25,
    "defending": 0,
    "raceStart": 0,
    "tyreMgmt": 15,
    "speed": 0,
    "cornering": 0,
    "powerUnit": 0,
    "pitTime": 10,
    "total": 50,
    "sourceIndex": 17
  },
  {
    "id": "firework",
    "name": "Firework",
    "overtaking": 15,
    "defending": 0,
    "raceStart": 15,
    "tyreMgmt": 0,
    "speed": 20,
    "cornering": 0,
    "powerUnit": 0,
    "pitTime": 0,
    "total": 50,
    "sourceIndex": 18
  },
  {
    "id": "frost",
    "name": "Frost",
    "overtaking": 0,
    "defending": 0,
    "raceStart": 15,
    "tyreMgmt": 25,
    "speed": 0,
    "cornering": 0,
    "powerUnit": 10,
    "pitTime": 0,
    "total": 50,
    "sourceIndex": 19
  },
  {
    "id": "full_send",
    "name": "Full Send",
    "overtaking": 5,
    "defending": 0,
    "raceStart": 0,
    "tyreMgmt": 0,
    "speed": 25,
    "cornering": 0,
    "powerUnit": 20,
    "pitTime": 0,
    "total": 50,
    "sourceIndex": 20
  },
  {
    "id": "genesis",
    "name": "Genesis",
    "overtaking": 0,
    "defending": 25,
    "raceStart": 0,
    "tyreMgmt": 0,
    "speed": 10,
    "cornering": 15,
    "powerUnit": 0,
    "pitTime": 0,
    "total": 50,
    "sourceIndex": 21
  },
  {
    "id": "ghoulfuel",
    "name": "Ghoulfuel",
    "overtaking": 25,
    "defending": 0,
    "raceStart": 0,
    "tyreMgmt": 0,
    "speed": 0,
    "cornering": 0,
    "powerUnit": 10,
    "pitTime": 15,
    "total": 50,
    "sourceIndex": 22
  },
  {
    "id": "gladiator",
    "name": "Gladiator",
    "overtaking": 0,
    "defending": 25,
    "raceStart": 15,
    "tyreMgmt": 0,
    "speed": 0,
    "cornering": 0,
    "powerUnit": 10,
    "pitTime": 0,
    "total": 50,
    "sourceIndex": 23
  },
  {
    "id": "glitz",
    "name": "Glitz",
    "overtaking": 15,
    "defending": 0,
    "raceStart": 0,
    "tyreMgmt": 0,
    "speed": 0,
    "cornering": 15,
    "powerUnit": 20,
    "pitTime": 0,
    "total": 50,
    "sourceIndex": 24
  },
  {
    "id": "handlebar",
    "name": "Handlebar",
    "overtaking": 0,
    "defending": 25,
    "raceStart": 0,
    "tyreMgmt": 15,
    "speed": 0,
    "cornering": 10,
    "powerUnit": 0,
    "pitTime": 0,
    "total": 50,
    "sourceIndex": 25
  },
  {
    "id": "heartbreaker",
    "name": "Heartbreaker",
    "overtaking": 15,
    "defending": 0,
    "raceStart": 20,
    "tyreMgmt": 0,
    "speed": 20,
    "cornering": 0,
    "powerUnit": 0,
    "pitTime": 0,
    "total": 55,
    "sourceIndex": 26
  },
  {
    "id": "herald",
    "name": "Herald",
    "overtaking": 10,
    "defending": 0,
    "raceStart": 25,
    "tyreMgmt": 0,
    "speed": 0,
    "cornering": 15,
    "powerUnit": 0,
    "pitTime": 0,
    "total": 50,
    "sourceIndex": 27
  },
  {
    "id": "hex",
    "name": "Hex",
    "overtaking": 20,
    "defending": 0,
    "raceStart": 0,
    "tyreMgmt": 0,
    "speed": 15,
    "cornering": 0,
    "powerUnit": 0,
    "pitTime": 5,
    "total": 40,
    "sourceIndex": 28
  },
  {
    "id": "hook",
    "name": "Hook",
    "overtaking": 0,
    "defending": 15,
    "raceStart": 10,
    "tyreMgmt": 0,
    "speed": 0,
    "cornering": 25,
    "powerUnit": 0,
    "pitTime": 0,
    "total": 50,
    "sourceIndex": 29
  },
  {
    "id": "impact",
    "name": "Impact",
    "overtaking": 15,
    "defending": 0,
    "raceStart": 0,
    "tyreMgmt": 0,
    "speed": 10,
    "cornering": 0,
    "powerUnit": 5,
    "pitTime": 0,
    "total": 30,
    "sourceIndex": 30
  },
  {
    "id": "instinct",
    "name": "Instinct",
    "overtaking": 0,
    "defending": 0,
    "raceStart": 10,
    "tyreMgmt": 5,
    "speed": 0,
    "cornering": 0,
    "powerUnit": 15,
    "pitTime": 0,
    "total": 30,
    "sourceIndex": 31
  },
  {
    "id": "iron_force",
    "name": "Iron Force",
    "overtaking": 0,
    "defending": 20,
    "raceStart": 0,
    "tyreMgmt": 10,
    "speed": 0,
    "cornering": 0,
    "powerUnit": 20,
    "pitTime": 0,
    "total": 50,
    "sourceIndex": 32
  },
  {
    "id": "kawaii",
    "name": "Kawaii",
    "overtaking": 0,
    "defending": 0,
    "raceStart": 15,
    "tyreMgmt": 0,
    "speed": 0,
    "cornering": 20,
    "powerUnit": 0,
    "pitTime": 15,
    "total": 50,
    "sourceIndex": 33
  },
  {
    "id": "launch_pad",
    "name": "Launch Pad",
    "overtaking": 0,
    "defending": 0,
    "raceStart": 25,
    "tyreMgmt": 0,
    "speed": 0,
    "cornering": 0,
    "powerUnit": 15,
    "pitTime": 10,
    "total": 50,
    "sourceIndex": 34
  },
  {
    "id": "lumberjack",
    "name": "Lumberjack",
    "overtaking": 0,
    "defending": 15,
    "raceStart": 0,
    "tyreMgmt": 10,
    "speed": 0,
    "cornering": 0,
    "powerUnit": 0,
    "pitTime": 25,
    "total": 50,
    "sourceIndex": 35
  },
  {
    "id": "merlion",
    "name": "Merlion",
    "overtaking": 0,
    "defending": 0,
    "raceStart": 0,
    "tyreMgmt": 0,
    "speed": 15,
    "cornering": 25,
    "powerUnit": 0,
    "pitTime": 10,
    "total": 50,
    "sourceIndex": 36
  },
  {
    "id": "movember",
    "name": "Movember",
    "overtaking": 0,
    "defending": 15,
    "raceStart": 0,
    "tyreMgmt": 10,
    "speed": 0,
    "cornering": 25,
    "powerUnit": 0,
    "pitTime": 0,
    "total": 50,
    "sourceIndex": 37
  },
  {
    "id": "nazar",
    "name": "Nazar",
    "overtaking": 0,
    "defending": 0,
    "raceStart": 20,
    "tyreMgmt": 15,
    "speed": 0,
    "cornering": 15,
    "powerUnit": 0,
    "pitTime": 0,
    "total": 50,
    "sourceIndex": 38
  },
  {
    "id": "oud",
    "name": "Oud",
    "overtaking": 15,
    "defending": 0,
    "raceStart": 0,
    "tyreMgmt": 0,
    "speed": 0,
    "cornering": 10,
    "powerUnit": 0,
    "pitTime": 25,
    "total": 50,
    "sourceIndex": 39
  },
  {
    "id": "palm",
    "name": "Palm",
    "overtaking": 0,
    "defending": 20,
    "raceStart": 10,
    "tyreMgmt": 20,
    "speed": 0,
    "cornering": 0,
    "powerUnit": 0,
    "pitTime": 0,
    "total": 50,
    "sourceIndex": 40
  },
  {
    "id": "pretzel",
    "name": "Pretzel",
    "overtaking": 0,
    "defending": 0,
    "raceStart": 0,
    "tyreMgmt": 25,
    "speed": 0,
    "cornering": 0,
    "powerUnit": 15,
    "pitTime": 10,
    "total": 50,
    "sourceIndex": 41
  },
  {
    "id": "prince",
    "name": "Prince",
    "overtaking": 0,
    "defending": 10,
    "raceStart": 20,
    "tyreMgmt": 0,
    "speed": 0,
    "cornering": 20,
    "powerUnit": 0,
    "pitTime": 0,
    "total": 50,
    "sourceIndex": 42
  },
  {
    "id": "pumpkin",
    "name": "Pumpkin",
    "overtaking": 0,
    "defending": 0,
    "raceStart": 10,
    "tyreMgmt": 20,
    "speed": 0,
    "cornering": 20,
    "powerUnit": 0,
    "pitTime": 0,
    "total": 50,
    "sourceIndex": 43
  },
  {
    "id": "rainbow",
    "name": "Rainbow",
    "overtaking": 0,
    "defending": 25,
    "raceStart": 5,
    "tyreMgmt": 0,
    "speed": 20,
    "cornering": 0,
    "powerUnit": 0,
    "pitTime": 0,
    "total": 50,
    "sourceIndex": 44
  },
  {
    "id": "reindeer",
    "name": "Reindeer",
    "overtaking": 0,
    "defending": 20,
    "raceStart": 0,
    "tyreMgmt": 0,
    "speed": 0,
    "cornering": 10,
    "powerUnit": 0,
    "pitTime": 20,
    "total": 50,
    "sourceIndex": 45
  },
  {
    "id": "rookie_reload",
    "name": "Rookie Reload",
    "overtaking": 5,
    "defending": 0,
    "raceStart": 0,
    "tyreMgmt": 0,
    "speed": 0,
    "cornering": 20,
    "powerUnit": 25,
    "pitTime": 0,
    "total": 50,
    "sourceIndex": 46
  },
  {
    "id": "rookie_rush",
    "name": "Rookie Rush",
    "overtaking": 0,
    "defending": 15,
    "raceStart": 10,
    "tyreMgmt": 25,
    "speed": 0,
    "cornering": 0,
    "powerUnit": 0,
    "pitTime": 0,
    "total": 50,
    "sourceIndex": 47
  },
  {
    "id": "rooster",
    "name": "Rooster",
    "overtaking": 20,
    "defending": 0,
    "raceStart": 20,
    "tyreMgmt": 0,
    "speed": 0,
    "cornering": 0,
    "powerUnit": 10,
    "pitTime": 0,
    "total": 50,
    "sourceIndex": 48
  },
  {
    "id": "samba",
    "name": "Samba",
    "overtaking": 0,
    "defending": 0,
    "raceStart": 0,
    "tyreMgmt": 0,
    "speed": 5,
    "cornering": 0,
    "powerUnit": 25,
    "pitTime": 20,
    "total": 50,
    "sourceIndex": 49
  },
  {
    "id": "schooner",
    "name": "Schooner",
    "overtaking": 0,
    "defending": 10,
    "raceStart": 25,
    "tyreMgmt": 0,
    "speed": 0,
    "cornering": 0,
    "powerUnit": 0,
    "pitTime": 15,
    "total": 50,
    "sourceIndex": 50
  },
  {
    "id": "self_control",
    "name": "Self Control",
    "overtaking": 0,
    "defending": 0,
    "raceStart": 0,
    "tyreMgmt": 5,
    "speed": 0,
    "cornering": 5,
    "powerUnit": 5,
    "pitTime": 0,
    "total": 15,
    "sourceIndex": 51
  },
  {
    "id": "skull",
    "name": "Skull",
    "overtaking": 15,
    "defending": 0,
    "raceStart": 0,
    "tyreMgmt": 0,
    "speed": 25,
    "cornering": 0,
    "powerUnit": 10,
    "pitTime": 0,
    "total": 50,
    "sourceIndex": 52
  },
  {
    "id": "street_shark",
    "name": "Street Shark",
    "overtaking": 10,
    "defending": 0,
    "raceStart": 25,
    "tyreMgmt": 0,
    "speed": 15,
    "cornering": 0,
    "powerUnit": 0,
    "pitTime": 0,
    "total": 50,
    "sourceIndex": 53
  },
  {
    "id": "surf",
    "name": "Surf",
    "overtaking": 0,
    "defending": 0,
    "raceStart": 25,
    "tyreMgmt": 5,
    "speed": 0,
    "cornering": 0,
    "powerUnit": 20,
    "pitTime": 0,
    "total": 50,
    "sourceIndex": 54
  },
  {
    "id": "taurus",
    "name": "Taurus",
    "overtaking": 5,
    "defending": 0,
    "raceStart": 0,
    "tyreMgmt": 0,
    "speed": 20,
    "cornering": 0,
    "powerUnit": 25,
    "pitTime": 0,
    "total": 50,
    "sourceIndex": 55
  },
  {
    "id": "timeless",
    "name": "Timeless",
    "overtaking": 0,
    "defending": 0,
    "raceStart": 15,
    "tyreMgmt": 0,
    "speed": 10,
    "cornering": 25,
    "powerUnit": 0,
    "pitTime": 0,
    "total": 50,
    "sourceIndex": 56
  },
  {
    "id": "tire_water",
    "name": "Tire Water",
    "overtaking": 0,
    "defending": 0,
    "raceStart": 0,
    "tyreMgmt": 10,
    "speed": 0,
    "cornering": 5,
    "powerUnit": 0,
    "pitTime": 5,
    "total": 20,
    "sourceIndex": 57
  },
  {
    "id": "tsar",
    "name": "Tsar",
    "overtaking": 0,
    "defending": 10,
    "raceStart": 0,
    "tyreMgmt": 25,
    "speed": 0,
    "cornering": 15,
    "powerUnit": 0,
    "pitTime": 0,
    "total": 50,
    "sourceIndex": 58
  },
  {
    "id": "tulip",
    "name": "Tulip",
    "overtaking": 0,
    "defending": 10,
    "raceStart": 0,
    "tyreMgmt": 0,
    "speed": 20,
    "cornering": 0,
    "powerUnit": 0,
    "pitTime": 20,
    "total": 50,
    "sourceIndex": 59
  },
  {
    "id": "tune_in",
    "name": "Tune-In",
    "overtaking": 0,
    "defending": 0,
    "raceStart": 0,
    "tyreMgmt": 0,
    "speed": 10,
    "cornering": 15,
    "powerUnit": 0,
    "pitTime": 25,
    "total": 50,
    "sourceIndex": 60
  },
  {
    "id": "unstoppable",
    "name": "Unstoppable",
    "overtaking": 25,
    "defending": 0,
    "raceStart": 0,
    "tyreMgmt": 0,
    "speed": 15,
    "cornering": 0,
    "powerUnit": 10,
    "pitTime": 0,
    "total": 50,
    "sourceIndex": 61
  },
  {
    "id": "vice",
    "name": "Vice",
    "overtaking": 0,
    "defending": 25,
    "raceStart": 0,
    "tyreMgmt": 0,
    "speed": 10,
    "cornering": 0,
    "powerUnit": 15,
    "pitTime": 0,
    "total": 50,
    "sourceIndex": 62
  },
  {
    "id": "warrior",
    "name": "Warrior",
    "overtaking": 5,
    "defending": 5,
    "raceStart": 0,
    "tyreMgmt": 0,
    "speed": 10,
    "cornering": 0,
    "powerUnit": 0,
    "pitTime": 0,
    "total": 20,
    "sourceIndex": 63
  }
];
